spring:
    application:
        name: practiceProject
    profiles:
        active: local
#        Giới hạn kích thước file upload
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
# Hibernate
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        open-in-view: true
        show-sql: true
    thymeleaf:
        check-template-location: false
    # Misc
    main:
        banner-mode: off
        allow-bean-definition-overriding: true
---
# Optional logging
# logging.level.root=warn
# spring.jpa.show-sql=true
# logging.level.org.hibernate=ERROR
logging:
    level:
        org.hibernate.SQL: debug
        org.springframework.web.cors: DEBUG
        org.springframework.security.web.cors: DEBUG
---
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs.path: /api-docs

---
management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always
---
# Example external API endpoint
product:
    url: https://dummyjson.com
---
jwt:
    secret-key: ${JWT_SECRET_KEY:67566B59703573367639792F423F4528482B4D6251655468576D5A712904200112312312321}
    expiration-time: ${JWT_EXPIRATION_TIME_IN_MILISECONDS:300000}
